version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    container_name: scc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - "5431:5431"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: